site_name: TheoTown plugin documentation
theme:
  name: material
nav:
  - Welcome: index.md
  - "Getting started": getting-started.md
  - Drafts: drafts.md
  - "Plugin manifest": manifest.md
  # TODO: do this automatically
  - "Draft types":
    - Animation: draft-types/animation.md
    - Base: draft-types/base.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - "mkdocs_custom"
  - "admonition"
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search
