site_name: TheoTown plugin documentation
theme:
  name: material
nav:
  - Welcome: index.md
  - "Getting started": getting-started.md
  - Drafts: drafts.md
  - "Plugin manifest": manifest.md
  - "Draft types":
    - ... | flat | draft-types/*
  #- Objects:
  #  - ... | objects/spawners/*
  #  - ... | flat | objects/*
  #  - Spawners
  - "Objects":
    - Animation: objects/animation.md
    - "Frame animation indices": objects/frame-animation-indices.md
    - Frame: objects/frame.md
    - Meta: objects/meta.md
    - Smoke: objects/smoke.md
    - Spawners:
      - "Biome spawner": objects/spawners/biome-spawner.md
      - "Car spawner": objects/spawners/car-spawner.md
      - "Helicopter spawner": objects/spawners/helicopter-spawner.md
      - "Legacy spawner": objects/spawners/legacy-spawner.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - "mkdocs_custom"
  - "admonition"
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css