site_name: TheoTown plugin system
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes 
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
nav:
  - Home: index.md
  - "Getting started": getting-started.md
  - "Plugin manifest": manifest.md
  - Reference:
    - Drafts:
      - draft-types/index.md
      - ... | flat | draft-types/*
    #- Objects:
    #  - ... | objects/spawners/*
    #  - ... | flat | objects/*
    #  - Spawners
    - Objects:
      - objects/index.md
      - Animation: objects/animation.md
      - "Frame animation indices": objects/frame-animation-indices.md
      - Frame: objects/frame.md
      - Meta: objects/meta.md
      - Smoke: objects/smoke.md
      - Spawners:
        #- "Biome spawner": objects/spawners/biome-spawner.md
        - Car spawner: objects/spawners/car-spawner.md
        - Helicopter spawner: objects/spawners/helicopter-spawner.md
        #- "Legacy spawner": objects/spawners/legacy-spawner.md
  - Guides:
    - guides/index.md
    - Aadsa dasda sd: encryption.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

  - "mkdocs_custom"
  - "admonition"
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css