site_name: TheoTown plugin system
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes 
    - content.tooltips
    - content.footnote.tooltips
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
nav:
  - Home: index.md
  - Getting started:
    - getting-started/writing-a-sample-plugin.md
    - getting-started/installing.md
  - "Plugin manifest": manifest.md
  - Reference:
    - Drafts:
      - draft-types/index.md
      - ... | flat | draft-types/*
    #- Objects:
    #  - ... | objects/spawners/*
    #  - ... | flat | objects/*
    #  - Spawners
    - Attribute types:
      - attribute-types/index.md
      - attribute-types/base.md
      - Attribute collection: attribute-types/attribute-collection.md
      - Animation: attribute-types/animation.md
      - Car flags: attribute-types/car-flags.md
      - Color:
        - attribute-types/color/index.md
        - ... | flat | attribute-types/color/*
      - "Frame animation indices": attribute-types/frame-animation-indices.md
      - Frame: attribute-types/frame.md
      - Meta:
        - attribute-types/meta/index.md
        - ... | flat | attribute-types/meta/*
      - Smoke: attribute-types/smoke.md
      - Spawners:
        - ... | flat | attribute-types/spawners/*
    - Technical details:
      - Loading order: reference/technical/loading-order.md
  - Guides:
    - guides/index.md
    - ... | flat | guides/*
    - Graphics:
      - ... | flat | guides/graphics/*
    - Fun:
      - ... | flat | guides/fun/*
    - Scripting:
      - ... | flat | guides/scripting/*
    - OpenGL Shading Language:
      - ... | flat | guides/glsl/*
  - Resources:
    - resources/index.md
    - ... | flat | resources/*

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - "mkdocs_custom"
  - "admonition"
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
