site_name: TheoTown plugin documentation
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - "mkdocs_custom"
  - "admonition"
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search
